server {
    listen 80;

    location /health {
        access_log off;
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }

    location /1kb {
        alias /usr/share/nginx/html/1kb.bin;
        add_header Content-Type application/octet-stream;
    }

    location /100kb {
        alias /usr/share/nginx/html/100kb.bin;
        add_header Content-Type application/octet-stream;
    }

    location /1mb {
        alias /usr/share/nginx/html/1mb.bin;
        add_header Content-Type application/octet-stream;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
